load balancer

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,53 +1,90 @@
 #!/usr/bin/env bash
-# Configure Nginx to have a custom HTTP response header (on web-01 and web-02)
-# - The name of the custom HTTP header must be X-Served-By
-# - The value of the custom HTTP header must be the hostname of the server Nginx is running on
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# Install nginx
-    apt-get -y update &> /dev/null
-    apt-get -y install nginx &> /dev/null
-# Start nginx
-  service nginx start
+# uncomment to see the script run in action
+#set -x
 
-# Allow Nginx through the firewall
-  ufw allow 'Nginx HTTP'
+# colors
+blue='\e[1;34m'
+brown='\e[0;33m'
+green='\e[1;32m'
+reset='\033[0m'
 
-# Give the user ownership to website files
-  mkdir -p /var/www/html
-chown -R "$USER":"$USER" /var/www/html
-chmod -R 755 /var/www/html
+echo -e "${blue}Updating and doing some minor checks...${reset}\n"
 
-# Create index.html
-  echo "Hello World!" > /var/www/html/index.html
-# Create error page
-  echo "Ceci n'est pas une page" > /var/www/html/404.html
+function install() {
+	command -v "$1" &> /dev/null
 
-# Back up the default nginx configuration file
-  cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: ${brown}$1${reset}\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${green}${1} is already installed.${reset}\n"
+	fi
+}
 
-# Write the configuration to the default file
+install nginx #install nginx
+
+echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
 server_config=\
 "server {
-  listen 80 default_server;
-  listen [::]:80 default_server;
-  root /var/www/html;
-  index index.html index.htm index.nginx-debian.html;
-  server_name _;
-  location / {
-    try_files \$uri \$uri/ =404;
-  }
-  rewrite ^/redirect_me https://www.linkedin.com/in/noureldine-mohamed-aa1102271/ permanent;
-  error_page 404 /404.html;
-  location = /404.html {
-    root /var/www/html;
-    internal;
-  }
-  add_header X-Served-By \$hostname;
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
 }"
-# Add the configuration to the default file
-echo "$server_config" > /etc/nginx/sites-available/default
 
-# Create a symbolic link to the default file in the sites-enabled directory
-ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
-# Reload Nginx
-nginx -s reload
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
